// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBrFV4gLHraTXwSR-GfXWQCUa83v7VtTcU',
    appId: '1:445722473026:android:e2ae21cc837feb11a4b3db',
    messagingSenderId: '445722473026',
    projectId: 'alwattar-groups-school1',
    storageBucket: 'alwattar-groups-school1.appspot.com',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDo_Wu2ji8o9b5JPJ5W091T_2_1z9izN8M',
    appId: '1:445722473026:ios:c35ad64fa2f3b4e4a4b3db',
    messagingSenderId: '445722473026',
    projectId: 'alwattar-groups-school1',
    storageBucket: 'alwattar-groups-school1.appspot.com',
    iosBundleId: 'com.alwatar.admin.alwatarAdmin',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAdlF6U_nSIhErO5mXfjwYj2r6u8vpB__o',
    appId: '1:445722473026:web:5f920ca0180aa3f4a4b3db',
    messagingSenderId: '445722473026',
    projectId: 'alwattar-groups-school1',
    authDomain: 'alwattar-groups-school1.firebaseapp.com',
    storageBucket: 'alwattar-groups-school1.appspot.com',
    measurementId: 'G-JQDH5VE3K4',
  );
}